.env, .gitignore, config/DatabaseConfig.js, src/controllers/Controller.js, src/db/RUEatsRepository.js, src/routes/index.js, src/utils/response.js
Title: Add View Restaurants API
Description:
- Implemented the View Restaurants API.
- Most changes are formatting updates from the Prettier extension.
Please review the changes and provide any feedback. If everything looks good, kindly approve the PR. Thanks for your time!
=> Feature viewrestaurants

package.json, src/controllers/Controller.js, src/routes/index.js, src/validations/validateLocationData.js
Added API to get latitude and longitudes of a given provided address using the Google Maps API, to be used for navigation and tracking.
=> getLocation API Added

src/controllers/Controller.js, src/db/RUEatsRepository.js, src/routes/index.js
=> delivery-associate auth with registration and login

src/controllers/Controller.js, src/db/RUEatsRepository.js, src/routes/index.js
Added auth for Restaurant owners. Tested API access for order-notifications, such that only logged in restaurant-owners with the token can access.
=> APIs to create restaurant and login.

.env, src/controllers/Controller.js, src/db/RUEatsRepository.js, src/routes/index.js, src/validations/validateSetLocationData.js
Added the setLocation API and updated both the getLocation and setLocation APIs to authorize using the jwt authorization
=> getLocation and setLocation APIs added with jwt authorization

.env, package.json, schema/DBSchema.sql, src/controllers/Controller.js, src/db/RUEatsRepository.js, src/routes/index.js, src/validations/validateDeliveryAssociate.js
Use Google's API to fetch closest delivery associate from a source
=> fetch closest delivery associate

app.js, src/controllers/Controller.js, src/db/RUEatsRepository.js, src/routes/index.js, src/validations/validatePostRequests.js
View order history for restaurant of id 12 (orders table needs to be populated):
Add menu item:
Add review:
Respond to feedback:
Delete menu item:
View insights (blueprint, needs to be worked on):
=> Features registered user: add review, and restaurant: order history, respond to feedback,  add/delete menu items, view insights

.gitignore, package.json, public/payment-form.html, public/scripts/get-client-token.js, src/controllers/Controller.js, src/routes/index.js, src/validations/validatePaymentToken.js
Client side HTTP file requests a token from Stripe that is used to facilitate the transaction.
This token is sent to our server for the stripe.charge method.
=> Payment APIs

.env, src/controllers/Controller.js, src/db/RUEatsRepository.js, src/routes/index.js
**Pull Request Summary:**
This PR implements JWT authentication to ensure that only authorized restaurant owners can accept, reject, or update the status of orders through the new endpoint `/accept-decline-order/{restaurant_id}/{order_id}`. 
Also added `/get-active-orders/:restaurant_id/` to view all active orders of the restaurant. Active orders are of status = (0,1).
**Details:**
- **Route Addition:** Added a new PATCH route in `routes/index.js` to handle order status updates.
- **Controller Enhancement:** Updated `controller.js` to include a method `acceptOrDeclineOrder`, which includes JWT validation to authenticate the restaurant owner before processing the request.
- **Database Interaction:** Added a method in `RUEatsRepository.js` named `updateOrderStatus` to execute the status …
=> Feature restaurant accept/decline

package.json, src/controllers/Controller.js, src/db/RUEatsRepository.js, src/routes/index.js
=> email verification for user

spec/controller.spec.js
Added jasmine test for Delivery Associates
=> testing for delivery associates

public/user-profile.html, src/db/RUEatsRepository.js, src/routes/uiRoutes.js
=> user profile initial commit

src/controllers/Controller.js, src/db/RUEatsRepository.js, src/routes/index.js
=> added delivery associate email verification

public/user-profile.html
=> added udpate address functionality with PUT call

src/controllers/Controller.js, src/db/RUEatsRepository.js, src/routes/index.js
=> added restaurant owner email verification

public/cart.html, public/restaurant-menu.html, src/controllers/Controller.js, src/db/RUEatsRepository.js, src/routes/index.js, src/routes/uiRoutes.js
Started with cart UI as well, all work in progress.
=> Integrated cart updates to Restaurant menu and getCart API

public/order-history.html, src/controllers/Controller.js, src/db/RUEatsRepository.js, src/routes/index.js, src/routes/uiRoutes.js
- Added functionality for a user to view their order history, from where they can view details of their purchase and add a review.
- Made the option to view order history in the nav bar of a logged in user from their profile.
- Currently relying on arbitrary token, will need the authentication edit.
- Yet to add the fuinctionality to add reviews and check details, which will be updated soon
=> User Order History

public/restaurant-orders.html, src/controllers/Controller.js, src/db/RUEatsRepository.js, src/routes/index.js, src/routes/uiRoutes.js
added UI Path:
`/app/restaurants-orders/:restaurant_id`
added backed path for getting order details from `menu` and `orders_items` join:
`/get-active-orders/:restaurant_id/orders/:order_id`
Updated controller and dbRepo accordingly.
Restaurant can view its active orders in chronological order
"See order" button displays the entire order:
The restaurant can choose to accept, reject or complete the order once ready.
Reject order will ask for reconfirmation
=> Feature activeordersui

public/restaurant-orders.html, src/controllers/Controller.js, src/db/RUEatsRepository.js
Orders tab shows both active orders and order history:
Past orders have status shown to the restaurant:
=> Feature restaurant order history

src/controllers/Controller.js, src/db/RUEatsRepository.js
=> Fixing a bug

public/cart.html, public/restaurant-menu.html, src/controllers/Controller.js, src/db/RUEatsRepository.js, src/routes/index.js
=> Checking item inventory before checkout

public/order-history.html, src/db/RUEatsRepository.js
- Added a Track order button that will open the delivery associate's location once he picks up the order.
- Rearranged the UI slightly
- Ordered the orders from the DB query of getting the order history in descending order on the basis of order date.
- Implemented the edit button for the review so that a user cannot edit his prior review of the restaurant when having an active order.
=> Order-history Updates
